esphome:
  name: $name
  friendly_name: $friendly_name
  includes:
    - ir_sender.h
  libraries:
    - IRremoteESP8266
  min_version: 2023.12.6

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  variant: esp32s3

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: $ip_addr
    gateway: !secret gateway
    subnet: !secret subnet
  power_save_mode: none
  output_power: 20.5

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  on_message:
    topic: /ir/send/$name
    then:
      - light.turn_on: light_status
      - delay: 0s
      - lambda: |-
          send_ir(&x[0], x.size());
      - light.turn_off: light_status

i2c:
  sda: GPIO11
  scl: GPIO10

uart:
  baud_rate: 256000
  tx_pin: GPIO47
  rx_pin: GPIO48

ld2410:

sensor:
  - platform: bh1750
    name: Immunination
  - platform: hdc1080
    temperature:
      name: Temperature
    humidity:
      name: Humidity
  - platform: ld2410
    detection_distance:
      name: Detection Distance

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence

switch:
  - platform: ld2410
    bluetooth:
      name: ld2410 Bluetooth

number:
  - platform: ld2410
    timeout:
      name: Presence Timeout
    max_move_distance_gate:
      name: Max Move Distance Gate
    max_still_distance_gate:
      name: Max Still Distance Gate
    g0:
      move_threshold:
        name: g0 Move Threshold
      still_threshold:
        name: g0 Still Threshold
    g1:
      move_threshold:
        name: g1 Move Threshold
      still_threshold:
        name: g1 Still Threshold
    g2:
      move_threshold:
        name: g2 Move Threshold
      still_threshold:
        name: g2 Still Threshold
    g3:
      move_threshold:
        name: g3 Move Threshold
      still_threshold:
        name: g3 Still Threshold
    g4:
      move_threshold:
        name: g4 Move Threshold
      still_threshold:
        name: g4 Still Threshold
    g5:
      move_threshold:
        name: g5 Move Threshold
      still_threshold:
        name: g5 Still Threshold
    g6:
      move_threshold:
        name: g6 Move Threshold
      still_threshold:
        name: g6 Still Threshold
    g7:
      move_threshold:
        name: g7 Move Threshold
      still_threshold:
        name: g7 Still Threshold
    g8:
      move_threshold:
        name: g8 Move Threshold
      still_threshold:
        name: g8 Still Threshold

light:
  - platform: status_led
    id: light_status
    name: Status
    pin: GPIO12
    icon: "mdi:led-outline"

custom_component:
  - lambda: |-
      auto ir_sender = new IRSender();
      return {ir_sender};
